site_name: Calculation Docs

theme:
  name: "material"
  palette:
    scheme: slate
    primary: teal

plugins:
  - mkdocstrings

nav:
  - Calculation Docs: index.md
  - tutorials.md
  - How-To Guides: how-to-guides.md
  - reference.md
  - explanation.md
